import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect } from 'react';

import CasesSection from '../components/CasesSection';
import ClientSection from '../components/ClientSection';
import ContactSection from '../components/ContactSection';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import SecondHero from '../components/SecondHero';
import SplashScreen from '../components/SplashScreen';

const Home: NextPage = () => {
  const timeout = 3;
  useEffect(() => {
    document.body.style.overflow = 'hidden';
    setTimeout(() => {
      document.body.style.overflow = 'visible';
    }, (timeout - 1) * 1000);
  }, []);

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SplashScreen time={timeout} />
      <Navbar />

      <main>
        <Hero id="home" />
        <ClientSection id="clientes" />
        <SecondHero id="sobre" />
        <CasesSection id="casos" />
        <ContactSection id="contato" />
        <Footer />
      </main>
    </>
  );
};

export default Home;
